apiVersion: apps/v1
kind: Deployment
metadata:
  name: aequitas-deployment
  labels:
    name: aequitas-server
spec:
  replicas: 3
  selector:
    matchLabels:
      name: aequitas-server
  template:
    metadata:
      labels:
        app: aequitas-server
    spec:
      containers:
      - name: aequitas-deployment
        image: server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2220
        - containerPort: 2222
        - containerPort: 2224