
apiVersion: v1
kind: Service
metadata:
 name: aequitas-servers
spec:
 selector:
   name: aequitas-server
 ClusterIP: None
 ports:
 - name: 
   port: 80
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer